name: Angular

on:
  push:
    branches: [ "main" ]

env:
  AZURE_WEBAPP_NAME: nextlibapp    # application's name
  #AZURE_WEBAPP_PACKAGE_PATH: './nextlibapp'      # set this to the path to your web app project
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install and build
      run: |
        npm install --legacy-peer-deps
        npm run build
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        #package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        package: ./
